name: Build and Sign APK (Fully Automated)

on:
  push:
    branches:
      - master
      - genspark_ai_developer
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Get version info
      id: version
      run: |
        VERSION_NAME=$(grep "^\s*versionName" app/build.gradle | head -1 | awk '{print $2}' | tr -d "'" | tr -d '"')
        VERSION_CODE=$(grep "^\s*versionCode" app/build.gradle | head -1 | awk '{print $2}')
        COMMIT_SHORT=$(git rev-parse --short HEAD)
        BUILD_DATE=$(date +'%Y%m%d_%H%M%S')
        
        if [ -z "$VERSION_NAME" ] || [[ "$VERSION_NAME" == *"+"* ]] || [[ "$VERSION_NAME" == *"="* ]]; then
          VERSION_NAME="2.2.5.1"
        fi
        if [ -z "$VERSION_CODE" ] || [[ "$VERSION_CODE" == *"+"* ]] || [[ "$VERSION_CODE" == *"="* ]]; then
          VERSION_CODE="2251"
        fi
        
        VERSION_NAME=$(echo "$VERSION_NAME" | sed 's/[^0-9.]//g')
        VERSION_CODE=$(echo "$VERSION_CODE" | sed 's/[^0-9]//g')
        
        echo "Extracted Version Name: $VERSION_NAME"
        echo "Extracted Version Code: $VERSION_CODE"
        echo "Commit: $COMMIT_SHORT"
        echo "Build Date: $BUILD_DATE"
        
        echo "version_name=$VERSION_NAME" >> "$GITHUB_OUTPUT"
        echo "version_code=$VERSION_CODE" >> "$GITHUB_OUTPUT"
        echo "commit_short=$COMMIT_SHORT" >> "$GITHUB_OUTPUT"
        echo "build_date=$BUILD_DATE" >> "$GITHUB_OUTPUT"
    
    - name: Verify Keystore
      run: |
        echo "=== Checking keystore file ==="
        if [ -f app/DailyTask.jks ]; then
          echo "âœ“ Keystore file exists: app/DailyTask.jks"
          ls -lh app/DailyTask.jks
          
          # éªŒè¯ç­¾åé…ç½®
          echo ""
          echo "=== Verifying keystore info ==="
          keytool -list -v -keystore app/DailyTask.jks -storepass 123456789 -alias key0 2>&1 | head -20 || echo "Keystore verification skipped"
        else
          echo "âœ— ERROR: Keystore file not found!"
          exit 1
        fi
        
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Build Release APK (Signed)
      run: |
        echo "=== Building signed release APK ==="
        ./gradlew assembleRelease --stacktrace
        
        echo ""
        echo "=== Verifying APK signature ==="
        RELEASE_APK=$(find app/build/outputs/apk -type f -name "*.apk" -path "*/release/*" | head -n 1)
        if [ -n "$RELEASE_APK" ]; then
          echo "Found release APK: $RELEASE_APK"
          
          # éªŒè¯ç­¾å
          echo ""
          echo "Checking APK signature..."
          jarsigner -verify -verbose -certs "$RELEASE_APK" 2>&1 | head -30 || true
          
          # æ˜¾ç¤ºç­¾åè¯¦æƒ…
          echo ""
          echo "APK signature details:"
          apksigner verify --print-certs "$RELEASE_APK" 2>&1 || echo "apksigner not available, using keytool..."
        fi
        
    - name: Organize APK files
      run: |
        echo "=== APK Output Directory Structure ==="
        find app/build/outputs/apk -type f -name "*.apk"
        
        mkdir -p apk_output
        
        # Debug APK
        DEBUG_APK=$(find app/build/outputs/apk -type f -name "*.apk" -path "*/debug/*" | head -n 1)
        if [ -n "$DEBUG_APK" ]; then
          cp "$DEBUG_APK" "apk_output/DailyTask_${{ steps.version.outputs.version_name }}_debug_${{ steps.version.outputs.build_date }}.apk"
          echo "âœ“ Debug APK: $(basename $DEBUG_APK)"
          echo "  Size: $(ls -lh apk_output/*debug*.apk | awk '{print $5}')"
        fi
        
        # Release APK (Signed)
        RELEASE_APK=$(find app/build/outputs/apk -type f -name "*.apk" -path "*/release/*" | head -n 1)
        if [ -n "$RELEASE_APK" ]; then
          cp "$RELEASE_APK" "apk_output/DailyTask_${{ steps.version.outputs.version_name }}_release_signed_${{ steps.version.outputs.build_date }}.apk"
          echo "âœ“ Release APK (SIGNED): $(basename $RELEASE_APK)"
          echo "  Size: $(ls -lh apk_output/*release*.apk | awk '{print $5}')"
          
          # æœ€ç»ˆéªŒè¯
          echo ""
          echo "=== Final signature verification ==="
          jarsigner -verify "apk_output/DailyTask_${{ steps.version.outputs.version_name }}_release_signed_${{ steps.version.outputs.build_date }}.apk" && echo "âœ“âœ“âœ“ APK is properly signed! âœ“âœ“âœ“" || echo "âœ—âœ—âœ— WARNING: APK signature verification failed! âœ—âœ—âœ—"
        fi
        
        echo ""
        echo "=== Final APK files ==="
        ls -lh apk_output/
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: DailyTask-debug-${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.commit_short }}
        path: apk_output/*debug*.apk
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload Release APK (Signed)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: DailyTask-release-signed-${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.commit_short }}
        path: apk_output/*release*.apk
        retention-days: 90
        if-no-files-found: warn
        
    - name: Create Release Notes
      if: startsWith(github.ref, 'refs/tags/v')
      id: release_notes
      run: |
        cat > release_notes.md << 'EOF'
        ## ðŸŽ‰ DailyTask v${{ steps.version.outputs.version_name }} å‘å¸ƒ

        ### ðŸ“¦ æž„å»ºä¿¡æ¯
        - **ç‰ˆæœ¬å·**: ${{ steps.version.outputs.version_name }}
        - **ç‰ˆæœ¬ä»£ç **: ${{ steps.version.outputs.version_code }}
        - **æž„å»ºæ—¥æœŸ**: ${{ steps.version.outputs.build_date }}
        - **æäº¤å“ˆå¸Œ**: ${{ steps.version.outputs.commit_short }}
        - **Release APK**: âœ… å·²è‡ªåŠ¨ç­¾å

        ### âœ¨ æ ¸å¿ƒåŠŸèƒ½
        - âœ… é’‰é’‰è‡ªåŠ¨æ‰“å¡
        - âœ… ä¼ªç­å±æŽ§åˆ¶ï¼ˆæš—è‰²é®ç½©ï¼‰
        - âœ… è¿œç¨‹æŒ‡ä»¤æŽ§åˆ¶ï¼ˆæ¯å±/äº®å±ï¼‰
        - âœ… æ‰‹åŠ¨éŸ³é‡é”®åˆ‡æ¢
        - âœ… **å‘¨æœ«è‡ªåŠ¨æš‚åœæ‰“å¡**ï¼ˆæ–°åŠŸèƒ½ï¼‰
        - âœ… **èŠ‚å‡æ—¥è‡ªåŠ¨æš‚åœæ‰“å¡**ï¼ˆæ–°åŠŸèƒ½ï¼Œå†…ç½® 2026 å¹´æ•°æ®ï¼‰
        - âœ… **æ‰“å¡å®Œæˆè‡ªåŠ¨æ¢å¤æš—è‰²**ï¼ˆæ–°åŠŸèƒ½ï¼Œ10-30 ç§’éšæœºå»¶è¿Ÿï¼‰
        - âœ… Bugly å¼‚å¸¸æ—¥å¿—è®°å½•

        ### ðŸ“¥ ä¸‹è½½è¯´æ˜Ž
        - **DailyTask_xxx_debug.apk**: Debug ç‰ˆæœ¬ï¼ŒåŒ…å«è°ƒè¯•ä¿¡æ¯ï¼ŒæŽ¨èæµ‹è¯•ä½¿ç”¨
        - **DailyTask_xxx_release_signed.apk**: Release ç‰ˆæœ¬ï¼Œâœ… å·²ç­¾åä¼˜åŒ–ï¼ŒæŽ¨èç”Ÿäº§ä½¿ç”¨

        ### ðŸ“± å®‰è£…è¦æ±‚
        - Android 7.0 (API 26) æˆ–æ›´é«˜ç‰ˆæœ¬
        - éœ€è¦æŽˆäºˆé€šçŸ¥æƒé™å’Œæ‚¬æµ®çª—æƒé™

        ### ðŸ§ª æµ‹è¯•å»ºè®®
        1. æµ‹è¯•å‘¨æœ«/èŠ‚å‡æ—¥è‡ªåŠ¨æš‚åœåŠŸèƒ½
        2. æµ‹è¯•æ‰“å¡å®Œæˆè‡ªåŠ¨æ¢å¤æš—è‰²åŠŸèƒ½
        3. æµ‹è¯•è¿œç¨‹æŒ‡ä»¤å’Œæ‰‹åŠ¨åˆ‡æ¢å…¼å®¹æ€§

        ### ðŸ“š å®Œæ•´æ–‡æ¡£
        æŸ¥çœ‹è¯¦ç»†åŠŸèƒ½è¯´æ˜Žå’Œæµ‹è¯•æŒ‡å—ï¼Œè¯·è®¿é—®ä»“åº“ä¸­çš„ `COMPLETE_DELIVERY_REPORT.md`
        EOF
        
        cat release_notes.md
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          apk_output/*.apk
        body_path: release_notes.md
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Summary
      run: |
        echo "## ðŸŽ‰ APK ç¼–è¯‘æˆåŠŸï¼" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“¦ æž„å»ºä¿¡æ¯" >> $GITHUB_STEP_SUMMARY
        echo "- **ç‰ˆæœ¬åç§°**: ${{ steps.version.outputs.version_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ç‰ˆæœ¬ä»£ç **: ${{ steps.version.outputs.version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- **æäº¤å“ˆå¸Œ**: ${{ steps.version.outputs.commit_short }}" >> $GITHUB_STEP_SUMMARY
        echo "- **æž„å»ºæ—¶é—´**: ${{ steps.version.outputs.build_date }}" >> $GITHUB_STEP_SUMMARY
        echo "- **åˆ†æ”¯**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Release APK**: âœ… å·²è‡ªåŠ¨ç­¾å" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“¥ ä¸‹è½½ APK" >> $GITHUB_STEP_SUMMARY
        echo "è¯·åœ¨ä¸Šæ–¹ **Artifacts** åŒºåŸŸä¸‹è½½ç¼–è¯‘å¥½çš„ APK æ–‡ä»¶" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Debug APK**: ç”¨äºŽå¼€å‘è°ƒè¯•ï¼ˆåŒ…å«è°ƒè¯•ä¿¡æ¯ï¼‰" >> $GITHUB_STEP_SUMMARY
        echo "- **Release APK**: âœ… å·²ç­¾åä¼˜åŒ–ï¼Œå¯ç›´æŽ¥å®‰è£…" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          echo "### ðŸš€ GitHub Release" >> $GITHUB_STEP_SUMMARY
          echo "å·²è‡ªåŠ¨åˆ›å»º GitHub Releaseï¼Œå¯åœ¨ Releases é¡µé¢ä¸‹è½½" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ‘‰ https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY
        fi
